// Curated high-resolution archival and editorial works of Marvelous Salon & Academy
// Clean, Apple-style metadata: visual primacy, zero clutter, concise titles

export const GALLERY_ITEMS = [
  // 1. Haute Bridal & Couture Occasions
  {
    id: 1,
    src: "/assets/gallery-bridal.jpg",
    title: "Haute Bridal Silhouette",
    subtitle: "Bespoke Hair & Floral Couture",
    category: "bridal",
    year: "2024",
    featured: true,
  },
  {
    id: 2,
    src: "/assets/gallery/marvelous_art_01.jpg",
    title: "Editorial Bridal Transformation",
    subtitle: "Artistry by MUA Bhavna Pahwa",
    category: "bridal",
    year: "2018",
  },
  {
    id: 3,
    src: "/assets/gallery/marvelous_art_58.jpg",
    title: "Signature Atelier Bridal Crown",
    subtitle: "Haute Occasion Coiffure",
    category: "bridal",
    year: "Heritage",
  },
  {
    id: 4,
    src: "/assets/gallery/marvelous_art_40.jpg",
    title: "Imperial Bridal Finery",
    subtitle: "Traditional Wedding Styling",
    category: "bridal",
    year: "2019",
  },
  {
    id: 5,
    src: "/assets/gallery/marvelous_art_17.jpg",
    title: "Modern Occasion Silhouette",
    subtitle: "Sculpted Texture & Veil",
    category: "bridal",
    year: "2018",
  },
  {
    id: 6,
    src: "/assets/gallery/marvelous_art_36.jpg",
    title: "Royal Wedding Makeover",
    subtitle: "Jewelled Atelier Artistry",
    category: "bridal",
    year: "2020",
  },

  // 2. Miss Multinational & International Pageants
  {
    id: 7,
    src: "/assets/gallery/marvelous_art_03.jpg",
    title: "Miss USA 2018 · World Winner",
    subtitle: "Official Crowning Makeover by Bhavna Pahwa",
    category: "pageant",
    year: "2018",
    featured: true,
  },
  {
    id: 8,
    src: "/assets/gallery/marvelous_art_04.jpg",
    title: "Miss Multinational Mexico",
    subtitle: "Tania Morales · Pageant Glamour",
    category: "pageant",
    year: "2018",
  },
  {
    id: 9,
    src: "/assets/gallery/marvelous_art_13.jpg",
    title: "Miss Multinational India",
    subtitle: "Simran Sharma · Atelier Coiffure",
    category: "pageant",
    year: "2018",
  },
  {
    id: 10,
    src: "/assets/gallery/marvelous_art_20.jpg",
    title: "Miss Multinational Myanmar",
    subtitle: "International Delegate Styling",
    category: "pageant",
    year: "2018",
  },
  {
    id: 11,
    src: "/assets/gallery/marvelous_art_23.jpg",
    title: "Miss Multinational Malaysia",
    subtitle: "Global Pageant Partnership",
    category: "pageant",
    year: "2018",
  },
  {
    id: 12,
    src: "/assets/gallery/marvelous_art_14.jpg",
    title: "Miss Multinational World Finale",
    subtitle: "Official Hair & Beauty Partner",
    category: "pageant",
    year: "2018",
  },

  // 3. Celebrity Transformations & National Awards (Verified Archival Photography)
  {
    id: 13,
    src: "/assets/celebrities/bhavna-mahima.jpg",
    title: "Mahima Chaudhary with Founder Bhavna Pahwa",
    subtitle: "Bollywood Icon & Screen Muse · Celebrity Sanctuary Artistry",
    category: "celebrity",
    year: "Archival",
    featured: true,
  },
  {
    id: 14,
    src: "/assets/celebrities/bhavna-sana-khan.jpg",
    title: "Sana Khan with Founder Bhavna Pahwa",
    subtitle: "Haute Red-Carpet Transformation & Styling Excellence",
    category: "celebrity",
    year: "Archival",
    featured: true,
  },
  {
    id: 15,
    src: "/assets/celebrities/ashna-gulshan-grover.jpg",
    title: "Gulshan Grover Presenting to Ashna Pahwa",
    subtitle: "Dazzling Star Award · Bollywood Industry Recognition",
    category: "celebrity",
    year: "Archival",
    featured: true,
  },
  {
    id: 16,
    src: "/assets/celebrities/ashna-mahima-award.jpg",
    title: "Glam India Award · Presented by Mahima Chaudhary",
    subtitle: "Ashna Pahwa · BRO Business Awards Excellence Honors",
    category: "celebrity",
    year: "2021",
    featured: true,
  },
  {
    id: 17,
    src: "/assets/celebrities/bhavna-mukul-dev.jpg",
    title: "Mukul Dev Presenting to Founder Bhavna Pahwa",
    subtitle: "National Salon Excellence in Beauty & Styling Award",
    category: "celebrity",
    year: "Archival",
  },
  {
    id: 171,
    src: "/assets/celebrities/celebrity-stage-ensemble.jpg",
    title: "National Bollywood Film & Season Awards Gala",
    subtitle: "Gulshan Grover, Sana Khan, Mahima Chaudhary, Simran Kaur, Rajniesh Duggall & Founder Bhavna Pahwa",
    category: "celebrity",
    year: "National Gala Honors",
    featured: true,
  },

  // 4. Haute Coiffure & Trichology
  {
    id: 18,
    src: "/assets/gallery-balayage.jpg",
    title: "Dimensional Balayage Waves",
    subtitle: "Bespoke Champagne Ribbons",
    category: "hair",
    year: "2024",
    featured: true,
  },
  {
    id: 19,
    src: "/assets/gallery-bob.jpg",
    title: "Architectural Precision Cut",
    subtitle: "Geometric Movement & Form",
    category: "hair",
    year: "2024",
  },
  {
    id: 20,
    src: "/assets/gallery-trichology.jpg",
    title: "Restorative Scalp Trichology",
    subtitle: "Cellular Diagnostic & Botanical Infusion",
    category: "hair",
    year: "2024",
  },
  {
    id: 21,
    src: "/assets/gallery/marvelous_art_35.jpg",
    title: "Schwarzkopf Professional Showcase",
    subtitle: "Artistic Direction & Tones",
    category: "hair",
    year: "2021",
  },

  // 5. Academy & Masterclasses
  {
    id: 22,
    src: "/assets/academy-masterclass.jpg",
    title: "Florian Hurel Masterclass",
    subtitle: "Celebrity Hair Maestro & Schwarzkopf Pro",
    category: "academy",
    year: "2022",
    featured: true,
  },
  {
    id: 23,
    src: "/assets/academy-laboratory.jpg",
    title: "The Styling Laboratory",
    subtitle: "Marvelous Salon Academy Suites",
    category: "academy",
    year: "2023",
  },
  {
    id: 24,
    src: "/assets/gallery/marvelous_art_09.jpg",
    title: "Professional Diploma Convocation",
    subtitle: "Advanced Hair & Makeup Certification",
    category: "academy",
    year: "2019",
  },
  {
    id: 25,
    src: "/assets/gallery/marvelous_art_37.jpg",
    title: "Hands-on Trichology Training",
    subtitle: "Live Workshop Pedagogy",
    category: "academy",
    year: "2020",
  },
  {
    id: 26,
    src: "/assets/gallery/marvelous_art_48.jpg",
    title: "Master Makeup Artistry Session",
    subtitle: "Editorial Look Construction",
    category: "academy",
    year: "2021",
  },

  // 6. Flagship Atelier Sanctuaries
  {
    id: 27,
    src: "/assets/marvelous-salon-hero.png",
    title: "Flagship Atelier Architecture",
    subtitle: "Arched Mirrors & Ivory Styling Suites",
    category: "sanctuary",
    year: "2024",
    featured: true,
  },
  {
    id: 28,
    src: "/assets/gallery/marvelous_art_38.jpg",
    title: "Ashok Vihar Illuminated Facade",
    subtitle: "Flagship Architectural Presence",
    category: "sanctuary",
    year: "2019",
  },
  {
    id: 29,
    src: "/assets/gallery/marvelous_art_56.jpg",
    title: "Private Consultation Sanctuary",
    subtitle: "Quiet Luxury Styling Rooms",
    category: "sanctuary",
    year: "2023",
  },
  {
    id: 30,
    src: "/assets/gallery/marvelous_art_46.jpg",
    title: "VIP Hair & Spa Suites",
    subtitle: "Bespoke Client Experience",
    category: "sanctuary",
    year: "2021",
  },
];

export const GALLERY_CATEGORIES = [
  { id: "all", label: "All Works" },
  { id: "bridal", label: "Bridal Couture" },
  { id: "pageant", label: "Pageants" },
  { id: "celebrity", label: "Celebrity" },
  { id: "hair", label: "Coiffure" },
  { id: "academy", label: "Academy" },
  { id: "sanctuary", label: "Atelier" },
];
